fix startup code for --clean-env

diff --git a/mulle-template b/mulle-template
--- a/mulle-template
+++ b/mulle-template
@@ -1,4 +1,4 @@
-#! /usr/bin/env mulle-bash
+#! /bin/sh
 # shellcheck shell=bash
 #
 #   Copyright (c) 2018 Nat! - Mulle kybernetiK
@@ -32,9 +32,82 @@
 #
 [ "${TRACE}" = 'YES' -o "${MULLE_TEMPLATE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
+#
+# restart with clean environment (still in bourne shell)
+#
+case "$1" in
+   --clean-env)
+      shift
 
-MULLE_EXECUTABLE_VERSION=1.0.1
+      if [ "${TRACE}" = 'YES' -o "${MULLE_TEMPLATE_TRACE}" = 'YES' ]
+      then
+         exec env -i \
+               TRACE="YES" \
+               PATH="$PATH" \
+                "$0" "$@"
+      fi
+
+      exec env -i \
+               PATH="$PATH" \
+               "$0" "$@"
+   ;;
+esac
+
+
+MULLE_EXECUTABLE_VERSION=1.0.2
 MULLE_EXECUTABLE_BASHFUNCTIONS="3.2"
+
+##
+## MEMO: need the old way here because of --clean-env booter
+##
+
+##########################################################################
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
+###########################################################################
+# #
+# # PRELUDE - Standard startup code for loading mulle-bashfunctions
+# #
+###
+
+#
+# Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
+#
+if ! [ ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR+x} ]
+then
+   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
+   export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
+fi
+
+#
+# The booter reruns the executable either with bash or zsh, whatever the
+# system provides. On the second run --no-auto-shell will be set first.
+#
+if [ "${1:-}" != --no-auto-shell ]
+then
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Include mulle-bashfunctions.sh         : default functions
+#         mulle-bashfunctions-none.sh    : almost no functions
+#         mulle-bashfunctions-minimal.sh : few functions for basic scripts
+#         mulle-bashfunctions-all.sh     : everything, even obscure functions
+#
+# Do this first to get aliases
+#
+MULLE_EXECUTABLE="${BASH_SOURCE[0]:-${(%):-%x}}"
+. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
+
+###
+# # Now we are in bash or zsh with mulle-bashfunctions loaded
+# #
+###########################################################################
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
+###########################################################################
+
 
 #
 # Determine location of own libexec directory. Which is `src` in development
@@ -197,21 +270,6 @@ template::set_custom_environment()
 
 template::main()
 {
-   local MULLE_FLAG_MAGNUM_FORCE='NO'
-
-   # technical flags
-   local MULLE_TRACE
-   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
-   local MULLE_FLAG_LOG_LOCAL='NO'
-   local MULLE_FLAG_LOG_DEBUG='NO'
-   local MULLE_FLAG_LOG_EXEKUTOR='NO'
-   local MULLE_FLAG_LOG_FLUFF='NO'
-   local MULLE_FLAG_LOG_SCRIPTS='NO'
-   local MULLE_FLAG_LOG_SETTINGS='NO'
-   local MULLE_FLAG_LOG_VERBOSE='NO'
-   local MULLE_FLAG_LOG_MERGE='NO'
-   local MULLE_TRACE_POSTPONE='NO'
-
    local defines
 
    #
@@ -265,7 +323,9 @@ template::main()
             [ $# -eq 1 ] && fail "Missing argument to \"$1\""
             shift
 
-            . "$1" || fail "Reading $1 produced $? as return value, indicating failure"
+            # needed for zsh
+            r_absolutepath "$1"
+            . "${RVAL}" || fail "Reading ${RVAL} produced $? as return value, indicating failure"
          ;;
 
          -*)
@@ -383,23 +443,5 @@ version"
    return $rval
 }
 
-case "$1" in
-   --clean-env)
-      shift
-
-      if [ "${TRACE}" = 'YES' -o "${MULLE_TEMPLATE_TRACE}" = 'YES' ]
-      then
-         exec env -i \
-               "TRACE=YES" \
-               "MULLE_BASHFUNCTIONS_LIBEXEC_DIR=${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" \
-               "MULLE_TEMPLATE_LIBEXEC_DIR=${MULLE_TEMPLATE_LIBEXEC_DIR}" \
-                "$0" "$@"
-      fi
-      exec env -i \
-               "MULLE_BASHFUNCTIONS_LIBEXEC_DIR=${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" \
-               "MULLE_TEMPLATE_LIBEXEC_DIR=${MULLE_TEMPLATE_LIBEXEC_DIR}" \
-               "$0" "$@"
-   ;;
-esac
 
 call_with_flags "template::main" "${MULLE_TEMPLATE_FLAGS}" "$@"
